-- ARTHunt Database Schema
-- Optimized for Real-time Spatial Tracking and Behavioral Data Collection

-- 1. Events Table: Stores the quest configuration and marker definitions
CREATE TABLE public.events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_name TEXT NOT NULL,
    creator_id UUID REFERENCES auth.users(id),
    markers JSONB NOT NULL, -- Array of objects: {id, name, clue, target_url, model_url}
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE
);

-- 2. Player Telemetry Table: Captures high-resolution behavioral data
CREATE TABLE public.player_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID REFERENCES public.events(id) ON DELETE CASCADE,
    participant_id TEXT NOT NULL,
    marker_id TEXT NOT NULL,
    detection_time TIMESTAMPTZ DEFAULT NOW(),
    delta_t_seconds FLOAT8, -- Time since previous marker
    hint_used BOOLEAN DEFAULT FALSE,
    dashcam_url TEXT, -- Link to the composite canvas upload in Supabase Storage
    metadata JSONB -- Browser info, device type, etc.
);

-- 3. Storage Buckets: Ensure these are created via the Supabase Dashboard
-- Bucket names: 'ar-assets' (Public), 'dashcam-blobs' (Private/Research only)

-- RLS Policies (Security)
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_telemetry ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read active events
CREATE POLICY "Public Read Access" ON public.events FOR SELECT USING (is_active = TRUE);

-- Allow participants to insert telemetry but not update/delete
CREATE POLICY "Participant Insert Access" ON public.player_telemetry FOR INSERT WITH CHECK (true);
